service: ecr-test
configValidationMode: off
provider:
  name: aws
  stage: prod
  region: ap-northeast-1
  logRetentionInDays: 30
  lambdaHashingVersion: 20201221
  ecr:
    images:
      baseimage:
        uri: ${ssm:AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/${ssm:MangumRepository}

functions:
  helloFunction:
    image: baseimage
    events:
      - http:
          integration: lambda-proxy
          path: /{proxy+}
          method: ANY
          cors: true
